version: '3.7'

services:
  frontend:
    container_name: admin_frontend
    image: antoniopapa1991/admin-frontend
    ports:
      - 8080:80
    depends_on:
      - backend
    networks:
      - app

  backend:
    container_name: admin_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app

  db:
    container_name: admin_db
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - app

  phpmyadmin:
    container_name: admin_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - db
    networks:
      - app

networks:
  app: